### PR TITLE
Fix for situation where the valueMap is empty to avoid ugly UI errors

### PR DESCRIPTION
**Pull request by BartReyserhove**
I had the issue in my app that my data set could be empty, and wanted to get rid of the not so nice error and just show the "No data" message. 

That is what this pull request does.

### CODE REVIEW

**Comment by mgroeneweg** [comment]
Thanks for the fix! I still need to update this widget to 9.24. I will merge and publish soon.

**Comment by BartReyserhove** [comment]
Great! Thanks Marcel.

**Comment by mgroeneweg** [comment]
I tried with the current widget in the test/demo app and it showed the normal message. How can I reproduce the situation where the widget breaks? Please provide more details or a test app. Your PR seems fine either way but I would like to see it break before I merge.

**Comment by BartReyserhove** [comment]
[Pivot_Test.zip](https://github.com/Itvisors/mendix-PivotTableWebWidget/files/12708165/Pivot_Test.zip)

I renamed the MPK file to a ZIP file. I can simulate the issue by starting this test app.

**Comment by mgroeneweg** [comment]
Are you sure this is the right thing?
image
I will test with my own tests anyway but I was wondering how you got this to work in the first place.

**Comment by mgroeneweg** [comment]
I saw your test app uses an XPath datasource. I tried it with a nonsense XPath and got the 'No data available message'. Maybe something changed in 9.24 causing this issue. I will first migrate to 9.24 and try again. Your PR looks fine but it should not be necessary.

**Comment by mgroeneweg** [comment]
I cannot reproduce the error, even after migration to 9.24.9, which I had planned anyway. Please provide a clear case that reproduces the error, also please provide the error message and stack you get.

**Comment by BartReyserhove** [comment]
I am indeed on 9.24.6. I also did not expected this to be necessary but for
some reason it did not show the "No data displayed" message.

**Comment by BartReyserhove** [comment]
Hi Marcel, did you not have the issue in the sample app I sent?

**Pull request closed without merging**
